export default {
  SELECTED_IMAGE: 'SELECTED_IMAGE',
  FLICKR_IMAGES_SUCCESS: 'FLICKR_IMAGES_SUCCESS',
  SELECTED_VIDEO: 'SELECTED_VIDEO',
  SHUTTER_VIDEOS_SUCCESS: 'SHUTTER_VIDEOS_SUCCESS',
  SEARCH_MEDIA_REQUEST: 'SEARCH_MEDIA_REQUEST',
  SEARCH_MEDIA_SUCCESS: 'SEARCH_MEDIA_SUCCESS',
  SEARCH_MEDIA_ERROR: 'SEARCH_MEDIA_ERROR',
};
